name: bean_tools
description: A dart tools.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
